version: '3.8'

services:
  web:
    build: .
    container_name: painel_clinica_web
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_tts:/app/static/tts
    # depends_on:
    #   - db # Descomente se usar Postgres

  # db: # Comentei o banco Postgres para salvar memória no Raspberry Pi 3
  #   image: postgres:13
  #   container_name: painel_clinica_db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_tts:
